# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!

pod 'Parse', '~>1.7.1'
pod 'ParseUI', '~>1.1.3'
pod 'Mantle', '2.0.3'
